version: '3'

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: crawler-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    image: mysql:5.6
    container_name: crawler-db
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=basedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root